print("Hello! Welcome to Band Name Generator.")
city = input("What city did you grow up in?\n")
pet_name = input("What is your pet's name?\n")
band_name = (city + " " + pet_name)
print("Your band name could be:", band_name)
